INFO     Logger:page.py:107 Page.visit() - Get URL: 'https://next.4zida.rs'
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09105f6d40>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09105f7580>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09105f6920>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
INFO     Logger:page.py:107 Page.visit() - Get URL: 'https://next.4zida.rs'
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09101b5db0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09101b5c30>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09101b5ab0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
INFO     Logger:page.py:107 Page.visit() - Get URL: 'https://next.4zida.rs'
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0910266e90>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0910266d40>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0910266740>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
INFO     Logger:page.py:107 Page.visit() - Get URL: 'https://next.4zida.rs'
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09102eff70>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09102efdc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09102ee560>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
INFO     Logger:page.py:107 Page.visit() - Get URL: 'https://next.4zida.rs'
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0910122770>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0910122530>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session
WARNING  urllib3.connectionpool:connectionpool.py:824 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f09101223e0>: Failed to establish a new connection: [Errno 111] Connection refused')': /wd/hub/session